// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using WebAppPortefolio.Data;

namespace WebAppPortefolio.Migrations
{
    [DbContext(typeof(PortefolioContext))]
    [Migration("20180703133148_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("WebAppPortefolio.Models.Utilizador", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Email");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Nome");

                    b.Property<string>("PasswordH");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.ToTable("Utilizadores");
                });
#pragma warning restore 612, 618
        }
    }
}
